### ISSUE TITLE
Consensus Call: Adopting Privacy-Preserving Attribution into PATCG

### ISSUE THREAD

**Issue by seanturner** [patcg/admin#26]
There was a formal consensus call to adopt the [Privacy-Preserving Attribution](https://private-attribution.github.io/api/) proposal into the PATCG repo, with the longer term intent to then transfer that repo to the PATWG repo once the PATWG is formally chartered.  The chairs judged that there was strong consensus to do this.  If you do not agree with this consensus, please let us know by commenting on this issue.  If you do object, please provide an alternative. The deadline for responses to this consensus call is Friday, 4 October 2024 @ 2359 UTC.

As was noted before the consensus call, the proposal in the repo is just a starting point.

**Comment by dmarti** [comment]
There are two issues that are important for me to be able to join a consensus on this.

1. Principle 3.2 in the [Private Ad Technologies Principles](https://patcg.github.io/docs-and-reports/principles/#researchers-regulators-and-auditors-should-be-able-to-investigate-how-a-system-is-used-and-whether-abuse-is-occurring) needs to clearly apply to the adfraud section.

> Researchers should be able to learn what measurements are taking place, in order to identify unexpected or potentially abusive behavior and to explain the implications of the system to users (whose individual data may not be satisfyingly explanatory).

 Attribution fraud is not just a problem for advertisers and for the legit sites whose attributions were "stolen."  The data practices behind attribution fraud can include risks and harms to users done in an effort to predict people likely to convert. The information sharing for researchers, regulators and auditors would need to be designed to make it clear where attribution fraud is happening. The more that attribution fraud can be made easily discoverable by researchers, regulators and auditors, the better off the users will be.

2. The specification should either require a minimum length for `impressionSites` in `measureConversion()` that will accept a typical large inclusion list (possibly on the order of thousands of sites) or the report process should be extended to accommodate a realistic and useful inclusion list length. (I can help with finding out about preferred inclusion list lengths at advertisers and agencies.)

**Comment by martinthomson** [comment]
@dmarti, we don't presently limit the length of anything, but would welcome proposals that set bounds or expectations for things like `impressionSites`.

I'm not clear on what you are saying about fraud.  The proposal obviously has some weaknesses in that area, which we acknowledged.  We'd be very happy to receive contributions that improve that situation.  Are you saying that we shouldn't do anything in this area unless we have an acceptable story for fraud?

**Comment by dmarti** [comment]
@martinthomson On fraud, I hope we can get to a consensus that Principle 3.2 applies. The goals of the proposal need to include making available the information that researchers, advertisers+service providers, and regulators would need in order to identify domains that are "stealing" conversions.

If the payoff for attribution fraud is attractive, then a lot of untrustworthy players have a lot of incentives to try to predict conversions that are likely to happen, and the known ways to do that involve surveillance (not by exploiting PPA itself, but using other surveillance practices on the same users whose impressions and conversions feed into PPA). The fraud problem does not need to mean not do anything in this area, but because of the surveillance risks to users from attempts at conversion "stealing" the anti-fraud reports would need to be working before or in parallel with conversion reports.

I don't want to see legit sites lose their conversions but that's not the main issue from the user POV -- the problem is what risks a user would be subjected to by parties trying to get a fraudulent impression in.

**Comment by martinthomson** [comment]
@dmarti I'm still struggling with taking those principles and turning them into something concrete.  Or at least, any more concrete than we have done so far.

The proposal explicitly has a weakness when it comes to faked impressions, which might enable more conversion stealing than is ideal.  That's an acknowledged shortcoming, but one that we have signaled an intent to address.

We have concrete proposals in the form of a "late binding" mode, in which impressions are collected separate from conversions.  This turns out to be considerably more expensive to operate, to the point that we aren't confident that all browsers will be able to offer an aggregation service that works for both advertisers and browsers.

Meta and Mozilla have investigated the use of three-party MPC and shown that a system based on that is likely feasible, despite the increase in volume that results.  A TEE can probably made do no matter what we do.  However, we haven't worked out the details to the point that we're confident in specifying that just yet.

If you have something more concrete to contribute, such as alternative approaches or tweaks to the existing one, that would be wonderful.  Is there something else?

**Comment by dmarti** [comment]
@martinthomson Yes, the other outstanding problem is concentration/centralization risks. A large platform company that is the recipient of lots of off-web surveillance data would be an ideal position to benefit from "stealing" attributions -- and, although a platform company would likely not do attribution stealing deliberately, an ML system trained to maximize PPA results would "learn" to do attribution stealing in a way that would be hard to figure out from the outside without a usable fraud reporting feature.

The ROI from PPA attribution fraud would tend to grow with platform size and surveillance capability, while legit conversions not only don't scale, they depend on the legit site being fortunate to get effective ads, and ad effectiveness is hard and difficult to predict in advance.

**Comment by eriktaubeneck** [comment]
@dmarti this consensus call is focused on adopting this document *as a draft* in the PATCG (and eventually the WG), in which it will continue to evolve. Fraud is certainly one of the many important factors that need to be continually considered as that spec evolves.

Can you clarify if you are objecting to adopting this doc, so that work can continue in the CG/WG? If you are objecting, can you please provide an alternative as @seanturner requested?

@seanturner and @AramZS - we're over a week past the stated deadline. Is there a plan to close this consensus call?

**Comment by dmarti** [comment]
@eriktaubeneck I object to adopting this proposal.

While PPA has a lot of good qualities viewed in isolation, the missing fraud reporting functionality means that it would create privacy and other risks for users if used on the real web. Users would also be indirectly harmed by other undesirable consequences of attribution going to fraudulent and/or monopolistic parties and not to legit sites.

Instead of proceeding with attempting to add fraud reporting features to this proposal (which may not be workable within advertiser budgets or sustainability goals), this group could build on [IAB Tech Lab ADMaP](https://iabtechlab.com/admap/) and extend it to make an attribution reporting system that is compatible with [Private Ad Technologies Principles](https://patcg.github.io/docs-and-reports/principles/).

(For example, see p. 15 of the spec: https://iabtechlab.com/wp-content/uploads/2024/10/ADMAP-Version-1.0-for-PUBLIC-COMMENT.pdf The "email address" and "phone number" key types are clearly not compatible with Principles, but an extended version could add an encrypted key type that a service, under control of the user, could resolve later.)

Currently ADMaP is further along on not just fraud issues, but also on industry contributions and requirements alignment. While ADMaP is not originally from W3C, and is not compatible with our Private Ad Technologies Principles as of version 1.0, at this point it already addresses some real-world privacy risks. This group now has an opportunity to work with the wider web advertising standards development community, not off in a separate space.

My suggested alternative is to adopt ADMaP v. 1.0 for discussion, and develop a fork,  with the understanding that it would be made available back to IAB Tech Lab for use by their members.

cc @seanturner @AramZS

**Comment by dmarti** [comment]
@wbl see the comment from @martinthomson above on the stealing problem.

In practice, the problem is that stealing conversions scales well and can be automated. The more data points you have on more people, the lower the cost to predict who's likely to buy something. Legit attribution, on the other hand, doesn't scale well. Making a site where people pay attention to the ad, and making an ad that sells, are both hard and hard to predict. So in an attribution system that is weak on fraud, the legit conversions will be swamped by stolen ones -- including both intentional fraud and ML that "learns" to do stealing and doesn't get caught.

**Comment by wbl** [comment]
I'm still not sure I really understand. This sounds like to get us on the same page you'd need a presentation or perhaps one has already been given and I missed it.

It's one thing if there is an impression recorded by a UA that never actually happened that ends up in attribution, or a conversion reported maliciously. It's quite another to deem it "stealing" to attribute a conversion to an impression that actually happened, but was selected because of propensity to buy the product advertised. Isn't that the point of online advertising, to have better information about where to show the ads? At what point is it appropriate smart selection vs. fraud? And I'm not sure why UA based mechanisms aren't able to handle this, or why the draft couldn't evolve after adoption to address your issues.

If the problem is that the impression shown isn't linked enough to the data that is used to attribute, I can think of some solid ways to address that like making the URL of the creative depend on that data. Why do you think this is a showstopper for this proposal?

**Comment by martinthomson** [comment]
@dmarti, this is the first time that anyone in this group has seriously suggested the use of AdMAP.  I was aware of efforts to build clean room solutions in IAB Tech Lab, but dismissed them.  Clean room options generally do not meet the principles we have set out.  AdMAP in its current form is completely unacceptable to Mozilla for that reason alone, though there are a number of things I can see offhand that seem likely introduce major problems[^1].

[^1]: I don't think it is a good use of time to seek to enumerate these given the vague nature of the proposal.  However, I will observe that the mapping system that is described is very vague.  Any system that seeks to provide genuine privacy would need to have a thorough and complete description of this component.  In the years we've been working on IPA, we have learned that this component is extremely hard -- if not impossible -- to get right.  I say this because there is a private set intersection design presented, which might be very similar to the first iteration of IPA.  We found that design to be vulnerable to a number of very serious attacks.

I can't test your claim about fraud mitigation in AdMAP.  The v1.0 specification you cite doesn't appear to have any material on that (the words "fraud or "steal" both get zero hits in the document).

For me to take this proposal more seriously, I would expect that a proponent (you, perhaps) would do the work to develop a more credible proposal, along the lines that @wbl describes.  It sounds like what you have in mind wouldn't be very much like AdMAP v1.0 at all anyway.

That leaves me with the conclusion that an objection to adopting the API is a suggestion that we continue to delay.  I can't support that outcome.

**Comment by therevoltingx** [comment]
@martinthomson this is Miguel from IAB TechLab. AdMAP is similar to IPA in that it uses a TEE to ensure that only aggregated reports are emitted from it. I am not familiar enough to know any fraud vectors it introduces vs AdMAP vs 3P Cookies.

TechLab would be happy to present AdMap in a future PATCG meeting and possibly exploring some sort of convergence path.

**Comment by martinthomson** [comment]
@therevoltingx, we'd have to be pretty clear on what sort of approach was being taken with respect to fraud for this to be worth the exercise.  That means a more fully-formed proposal would need to be developed.

As previously noted, a TEE doesn't meet the security requirements set out by some browsers, so that alone might be disqualifying.  I'm personally very skeptical about several other aspects of the design, as noted above, so am not confident that an acceptably strong solution could be developed.

**Comment by therevoltingx** [comment]
@martinthomson which browsers don't consider TEE acceptable? AFAIK Sandbox/Chrome uses it and even https://private-attribution.github.io/api/#aggregation-service mentions it. 

For mapping AdMAP uses Multi-Party Computation which PPA also mentions. So I'm unclear what, from a high level, disqualifies it. It seems that PPA also does not have a clear approach on fraud prevention as mentioned in the thread.

**Comment by michaelkleber** [comment]
Miguel: Both Firefox and Safari have indicated that they require Secure Multi-Party Computation for server-side implementations.

The past two years of work that this group has gone through, creating the Privacy-Preserving Attribution proposal that we want to adopt into the PATWG, has had a substantial focus on creating a design that can support _either TEE or MPC_ server-side implementations, so that the API can be shipped by browsers that require either kind of infrastructure.

**Comment by dmarti** [comment]
The impact on real users is what matters. Persisting with both an ADMAP track at IAB Tech Lab and a PPA track here would mean that future users would be stuck with the costs and risks of two half-done systems. We have the opportunity to try to avoid the situation where

 * sites have yet another reason to hassle users for their real email addresses or phone numbers, for ADMAP reports
 
 * parties collect additional personal data (on and off-web) in an effort to predict users' near-future shopping and "steal" PPA attribution

Both proposals need work—PPA, to address fraud, and ADMAP to support keying other than by email or phone. ADMAP, as is, offers better real-world privacy protection for users because of the fraud issue, and has more full-featured reporting that makes it workable for more publishers and advertisers.

PATCG/PATWG can have more impact by collaborating on ADMAP with a view to bringing it into line with this group's principles than by heading down a path that would make most parties deal with two systems—ADMAP for when both publisher and advertiser have an identifier for the user, and PPA as a fallback—with all the complexity and risks that would bring.

Right now the options are adopt PPA with its outstanding issues and work to improve it as just this group, or adopt ADMAP with its outstanding issues and work to improve it along with a wider group of sites, service providers, and others.

**Comment by wbl** [comment]
Don, the decision point here is about adoption as a starting point, not final. I don't see why the ad "fraud" issue (really last touch attribution) is so baked into PPA that it can't be addressed. We also don't have a rival AdMAP proposal here, just your suggestion we go work on one.

There's no reason IAB tech lab couldn't have put forward ADMAP here, and can still in the future, or influence the PPA specification to address these issues.

**Comment by AramZS** [comment]
Hello all here, I wanted to discuss a few things: 

1. While we welcome the IAB to present the AdMAP proposal to PAT, it is simply not relevant to this discussion. 

Wearing my hat as the contributor from The Washington Post for a moment, I do not believe it is particularly private by most definitions, it is just secure. No system that does one to one ID matching is really "private". AdMAP is a Clean-Room-Based solution, which means it handles one to one mapping of IDs. It cannot run in either a user Do Not Sell state nor in an Opt In region where the user has opted out in my opinion, since it is explicitly transmitting specific user IDs. 

Wearing my co-chair hat I don't see how it could possibly be considered 'more private' than any of the family of private measurement proposals that we've considered, much less the latest one. Considering our goals, our privacy principles, and the charter of the upcoming WG, I don't see how we could actually even pick up work on AdMAP--if the IAB brought it to us for standardization work in this context, which I can't see why they would--nor how it would be appropriate. AdMAP could be considered as potentially a system that could run along side other work this group outputs, or a consumer of the APIs that proposals might produce (though I can't see how with my current knowledge of it). At this point, I'd prefer this thread of conversation to drop discussion of AdMAP, I don't think it is relevant. 

2. In terms of fraud concerns, I see and hear them raised for this proposal. I think we can take up the proposal and prioritize addressing fraud concerns actively. I believe the specific innovations to the previous proposals around the privacy budget and correct structuring of the `impressionSites` field can give us better antifraud results then we have in the current marketplace to be honest. This can further be enhanced on the antifraud front when user agents have both this and other proposals in the antifraud working group online. The discussion around filtering during TPAC gave me a lot of confidence that there are properties that can be further worked on in this proposal to address your antifraud concerns @dmarti, though of course that development will take time and input like yours to make sure we get right. We can also bring online AdMAP discussions or any other anti-fraud measure discussions that participants might decide to leverage to further bring concerns around antifraud to the forefront. I don't think that PPA is lacking in hooks for, as @wbl notes ways for entities to be "applying their own integrity measurements to impressions or reports of conversions".

3. Wearing my co-chair hat I think I feel comfortable in saying that if we adopt the proposal we can have presentations and potentially, if you are willing to lead it @dmarti, an ad-hoc group specifically to make sure that PPA has antifraud measures that satisfy the wider group. 

I don't think there are any other objections to consensus here, but I'd like to make sure you feel like your concerns are addressed and that they will be incorporated into the documents we produce. @dmarti considering the time spent on this conversation thus far, I think could you respond on if you continue to hold up your objection here within the next three days (Thursday afternoon) and after that @seanturner and I will adjudicate on consensus.

**Comment by therevoltingx** [comment]
I really wasn't thinking of proposing AdMAP but rather just presenting it and seeing what it was in common with PPA and where the two could collab. For example, in PPA an impression is an "action" but in AdMap it is an "exposure". IMO "exposure" is better because an "action" denotes that a user did something which they didn't in an impression.

But if there is no interest in presenting AdMAP in a W3C that's fine, as you mentioned it's a standard for Data Clean Rooms. We looked at MPC for attribution but it was just not feasible so we focused on TEE. 

In either case, we will continue to engage with the W3C in the hope to help shape the upcoming attribution standards to help solve real-world publisher/advertiser use cases.

**Comment by eriktaubeneck** [comment]
> For example, in PPA an impression is an "action" but in AdMap it is an "exposure". IMO "exposure" is better because an "action" denotes that a user did something which they didn't in an impression.

Point taken that ["action"](https://private-attribution.github.io/api/#actions) could be better named, but it's definition includes exposure (and is even broader to include opportunities, in order to measure a control group for randomized controlled trials):

> Actions that are of interest to advertisers are primarily the showing of advertisements (also referred to as impressions). Other actions include ad clicks (or other interactions) and opportunities to show ads that were not taken.

***
To the larger conversation, I agree with the sentiment that AdMAP doesn't represent an alternative to PPA. Adopting the PPA draft into the CG/WG and continuing work on it doesn't exclude AdMAP from being presented to the group, or, if there were interest, adopting it into a different work item for the CG/WG.

**Comment by therevoltingx** [comment]
Ah yeah in that case neither exposure or action are perfect names. 

But yeah we'd be happy to present AdMAP at a high level so at the least we understand what aspects of it are not compatible with browser requirements. The main thing is that AdMAP does try to work within current browser restraints so it must use 1p identifiers unlike browser-native proposals. To make advertisers/publishers lives easier it would be great if the two would be somewhat compatible or at least use similar terms, schemas, etc.

**Comment by benjaminsavage** [comment]
> the report process should be extended to accommodate a realistic and useful inclusion list length

I think this is achievable. Given that the inclusion list is not going to affect the report size, but will simply be provided to the browser as a filter to use internally, I suspect we can support a very, very long length. @dmarti - if you could share some sample inclusion lists I think that would be very helpful.

**Comment by dmarti** [comment]
@AramZS thank you for the additional context. 

While I still see this proposal as adding an additional, unnecessary set of privacy risks for users, I understand that the group wants to discuss it. I withdraw my objection.

**Comment by dmarti** [comment]
@benjaminsavage A long filter list would be about 20,000 domains. I don't have access to one that long but will look. Thank you.

**Comment by AramZS** [comment]
The co-chairs have noted that the only objection was dropped and judge we have consensus on: "[adopting] the [Privacy-Preserving Attribution](https://private-attribution.github.io/api/) proposal into the PATCG repo, with the longer term intent to then transfer that repo to the PATWG repo once the PATWG is formally chartered."

At this time the co-chairs invite the authors to move the repo into the PATCG org space!

**Comment by eriktaubeneck** [comment]
Moved! The spec repo now lives at https://github.com/patcg/ppa-api

**Comment by AramZS** [comment]
Thank you @eriktaubeneck !
